[relaychain]
default_command = "./bin/polkadot-v0.9.37"
default_args = [ "-lparachain=debug" ]

chain = "wococo-local"
  # relaychain nodes are by default validators
  [[relaychain.nodes]]
  ws_port = 4242
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000
chain = "westmint-local"
cumulus_based = true

  [parachains.collator]
  ws_port = 4243
  name = "westmint-collator-01"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 1001
chain = "westmint-local"
cumulus_based = true

  [parachains.collator]
  ws_port = 4244
  name = "westmint-collator-02"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]

[[hrmp_channels]]
sender = 1000
recipient = 1001
max_capacity = 8
max_message_size = 8000

[[hrmp_channels]]
sender = 1001
recipient = 1000
max_capacity = 8
max_message_size = 8000
